# Generated by Django 2.2.10 on 2020-04-09 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='имя социальной сети')),
                ('href', models.CharField(default='#', max_length=128, verbose_name='ccылкана страницу социальной сети')),
                ('image', models.ImageField(blank=True, upload_to='products_images')),
                ('alt', models.CharField(max_length=24, unique=True, verbose_name='короткое имя')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления новости')),
                ('news_tite', models.CharField(max_length=64, unique=True, verbose_name='заголовок новости')),
                ('news_content', models.TextField(verbose_name='содержание статьи')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='имя сервиса')),
                ('content', models.TextField(verbose_name='описание сервиса')),
                ('image', models.ImageField(upload_to='products_images')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='имя')),
                ('post', models.CharField(max_length=32, verbose_name='должность')),
                ('image', models.ImageField(upload_to='products_images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='имя продукта')),
                ('desc', models.CharField(max_length=128, verbose_name='краткое описание продукта')),
                ('desc_long', models.TextField(blank=True, verbose_name='описание продукта')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('image', models.ImageField(blank=True, default='no-image.jpg', upload_to='products_images')),
                ('alt', models.CharField(blank=True, max_length=64, verbose_name='короткое имя продукта')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество товара')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='скидка на товара')),
                ('is_active', models.BooleanField(default=True, verbose_name='удален')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления товара')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения карточки товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductCategory')),
            ],
        ),
    ]
