# Generated by Django 2.2.10 on 2020-04-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsocial',
            name='href',
            field=models.CharField(default='#', max_length=128, verbose_name='ccылкана страницу социальной сети'),
        ),
    ]
