# Generated by Django 3.0.3 on 2020-04-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_fill_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='удален'),
        ),
    ]
