# Generated by Django 2.2.10 on 2020-04-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200408_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainMenu',
        ),
    ]
