# Generated by Django 2.2.10 on 2020-04-09 00:16

from django.db import migrations

def forwards_func(apps, schema_editor):
    
    pro_cat_model = apps.get_model("mainapp", "ProductCategory")
    prod_model = apps.get_model("mainapp", "Product")
    soc_model = apps.get_model("mainapp", "MainSocial")
    serv_model = apps.get_model("mainapp", "Services")
    news_model = apps.get_model("mainapp", "News")
    team_model = apps.get_model("mainapp", "Team")

    pro_cat_obj = pro_cat_model.objects.create(
        pk=1,
        name="action",
        description="Lorem Ipsum is simply dummy text of the printing and typesetting industry."
    )   

    prod_model.objects.create(
        pk=1,
        category=pro_cat_obj,
        name="BATTLEFIELD 1", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=21.16,
        image="products_images/battlefield-game.jpg", 
        alt="BATTLEFIELD 1",
        quantity=5,
        discount=0,
        is_active="True",
        created_at="2020-04-08 16:15:53.373277",
        updated_at="2020-04-08 16:15:53.373277",
    )
    prod_model.objects.create(
        pk=2,
        category=pro_cat_obj,
        name="BATTLEFIELD 4", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=38.41,
        image="products_images/battlefield4-game.jpg", 
        alt="BATTLEFIELD 4",
        quantity=15,
        discount=0,
        is_active="True",
        created_at="2020-04-02 16:15:53.373277",
        updated_at="2020-04-03 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=3,
        category=pro_cat_obj,
        name="ASSASIN’S CREED: Rogue", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=19.99,
        image="products_images/assassin-game.jpg", 
        alt="ASSASIN’S CREED: Rogue",
        quantity=8,
        discount=0,
        is_active="True",
        created_at="2020-04-05 16:15:53.373277",
        updated_at="2020-04-07 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=4,
        category=pro_cat_obj,
        name="FOR HONOR", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=25.57,
        image="products_images/for-honor-game.jpg", 
        alt="FOR HONOR",
        quantity=7,
        discount=0,
        is_active="True",
        created_at="2020-04-06 16:15:53.373277",
        updated_at="2020-04-08 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=5,
        category=pro_cat_obj,
        name="CALL OF DUTY:<br>Infinite Warface", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=28.89,
        image="products_images/call-duty-game.jpg", 
        alt="CALL OF DUTY",
        quantity=9,
        discount=0,
        is_active="True",
        created_at="2020-04-01 16:15:53.373277",
        updated_at="2020-04-03 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=6,
        category=pro_cat_obj,
        name="TOMB RAIDER", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=34.45,
        image="products_images/tom-raider-game.jpg", 
        alt="TOMB RAIDER",
        quantity=11,
        discount=0,
        is_active="True",
        created_at="2020-04-02 16:15:53.373277",
        updated_at="2020-04-04 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=7,
        category=pro_cat_obj,
        name="WORL OF WARCRAFT:<br>Wrath Of The Linch King", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=27.99,
        image="products_images/warcraft-game.jpg", 
        alt="WORL OF WARCRAFT: Wrath Of The Linch King",
        quantity=9,
        discount=0,
        is_active="True",
        created_at="2020-04-05 16:15:53.373277",
        updated_at="2020-04-06 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=8,
        category=pro_cat_obj,
        name="DOOM ETERNAL", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=24.99,
        image="products_images/doom-eternal-game.jpg", 
        alt="DOOM ETERNAL",
        quantity=7,
        discount=0,
        is_active="True",
        created_at="2020-04-07 16:15:53.373277",
        updated_at="2020-04-08 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=9,
        category=pro_cat_obj,
        name="inFAMOUS", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=19.15,
        image="products_images/infamous-game.jpg", 
        alt="inFAMOUS",
        quantity=11,
        discount=0,
        is_active="True",
        created_at="2020-04-05 16:15:53.373277",
        updated_at="2020-04-06 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=10,
        category=pro_cat_obj,
        name="DISHONORED 2", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=25.64,
        image="products_images/dishonored-similar-game.jpg", 
        alt="DISHONORED 2",
        quantity=6,
        discount=0,
        is_active="True",
        created_at="2020-04-02 16:15:53.373277",
        updated_at="2020-04-08 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=11,
        category=pro_cat_obj,
        name="THIEF", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=31.99,
        image="products_images/thief-similar-game.jpg", 
        alt="THIEF",
        quantity=9,
        discount=0,
        is_active="True",
        created_at="2020-04-01 16:15:53.373277",
        updated_at="2020-04-05 17:35:53.373277",
    )
    del pro_cat_obj

    pro_cat_obj = pro_cat_model.objects.create(
        pk=2,
        name="strategy",
        description="Lorem Ipsum is simply dummy text of the printing and typesetting industry."
    )

    prod_model.objects.create(
        pk=12,
        category=pro_cat_obj,
        name="STAR WARS:<br>Battlefront II", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=20.50,
        image="products_images/star-wars-game.jpg", 
        alt="STAR WARS",
        quantity=9,
        discount=0,
        is_active="True",
        created_at="2020-04-02 16:15:53.373277",
        updated_at="2020-04-06 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=13,
        category=pro_cat_obj,
        name="RYSE: Son Of Rome", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=29.99,
        image="products_images/ryse-game.jpg", 
        alt="RYSE",
        quantity=10,
        discount=0,
        is_active="True",
        created_at="2020-04-03 16:15:53.373277",
        updated_at="2020-04-04 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=14,
        category=pro_cat_obj,
        name="BATTLESTATION PACIFIC", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=17.65,
        image="products_images/ryse-game.jpg", 
        alt="BATTLESTATION PACIFIC",
        quantity=8,
        discount=0,
        is_active="True",
        created_at="2020-04-01 16:15:53.373277",
        updated_at="2020-04-08 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=15,
        category=pro_cat_obj,
        name="MIDDLE-EARTH:<br>Shadow Of War", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=21.78,
        image="products_images/shadow-similar-game.jpg", 
        alt="MIDDLE-EARTH",
        quantity=16,
        discount=0,
        is_active="True",
        created_at="2020-04-02 16:15:53.373277",
        updated_at="2020-04-07 17:35:53.373277",
    )
    del pro_cat_obj

    pro_cat_obj = pro_cat_model.objects.create(
        pk=3,
        name="simulator",
        description="Lorem Ipsum is simply dummy text of the printing and typesetting industry."
    )

    prod_model.objects.create(
        pk=16,
        category=pro_cat_obj,
        name="WORLD OF TANKS", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=18.60,
        image="products_images/world-tanks-game.jpg", 
        alt="WORLD OF TANKS",
        quantity=4,
        discount=0,
        is_active="True",
        created_at="2020-04-03 16:15:53.373277",
        updated_at="2020-04-08 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=17,
        category=pro_cat_obj,
        name="WORLD OF WARSHIPS", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=23.99,
        image="products_images/world-warships-game.jpg", 
        alt="WORLD OF WARSHIPS",
        quantity=8,
        discount=0,
        is_active="True",
        created_at="2020-04-04 16:15:53.373277",
        updated_at="2020-04-05 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=18,
        category=pro_cat_obj,
        name="UFC", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=21.15,
        image="products_images/ufc-game.jpg", 
        alt="UFC",
        quantity=16,
        discount=0,
        is_active="True",
        created_at="2020-04-05 16:15:53.373277",
        updated_at="2020-04-07 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=19,
        category=pro_cat_obj,
        name="HITMAN", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=37.89,
        image="products_images/hitman-similar-game.jpg", 
        alt="HITMAN",
        quantity=7,
        discount=0,
        is_active="True",
        created_at="2020-04-02 16:15:53.373277",
        updated_at="2020-04-06 17:35:53.373277",
    )
    del pro_cat_obj

    pro_cat_obj = pro_cat_model.objects.create(
        pk=4,
        name="sport",
        description="Lorem Ipsum is simply dummy text of the printing and typesetting industry."
    )
    
    prod_model.objects.create(
        pk=20,
        category=pro_cat_obj,
        name="CREW 2", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=16.99,
        image="products_images/crew-2-game.jpg", 
        alt="CREW 2",
        quantity=3,
        discount=0,
        is_active="True",
        created_at="2020-04-03 16:15:53.373277",
        updated_at="2020-04-04 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=21,
        category=pro_cat_obj,
        name="FIFA 12", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=27.65,
        image="products_images/fifa-12-game.jpg", 
        alt="FIFA 12",
        quantity=14,
        discount=0,
        is_active="True",
        created_at="2020-04-04 16:15:53.373277",
        updated_at="2020-04-05 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=22,
        category=pro_cat_obj,
        name="NEED for SPEED", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=23.99,
        image="products_images/need-for-speed-game.jpg", 
        alt="NEED for SPEED",
        quantity=7,
        discount=0,
        is_active="True",
        created_at="2020-04-01 16:15:53.373277",
        updated_at="2020-04-05 17:35:53.373277",
    )
    prod_model.objects.create(
        pk=23,
        category=pro_cat_obj,
        name="PROJECT CARS 2 cover", 
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        desc_long="The plot is set in a fictional history of real world events and follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.", 
        price=25.99,
        image="products_images/project-cars-2-game.jpg", 
        alt="PROJECT CARS 2 cover",
        quantity=11,
        discount=0,
        is_active="True",
        created_at="2020-04-02 16:15:53.373277",
        updated_at="2020-04-03 17:35:53.373277",
    )
    
    soc_model.objects.create(
        pk=1,
        name="fb",
        href="#", 
        image="img/social-fb.png", 
        alt="facebook",
    )
    soc_model.objects.create(
        pk=2,
        name="tw",
        href="#", 
        image="img/social-tw.png", 
        alt="twitter",
    )
    soc_model.objects.create(
        pk=3,
        name="rss",
        href="#", 
        image="img/social-rss.png", 
        alt="rss",
    )
    soc_model.objects.create(
        pk=4,
        name="vk",
        href="#", 
        image="img/social-vk.png", 
        alt="vk",
    )

    serv_model.objects.create(
        pk=1,
        title="Repreh Qui In Ea Voluptate",
        content="Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.", 
        image="img/pic-fork.png", 
    )
    serv_model.objects.create(
        pk=2,
        title="Aut Perferendis Doloribus",
        content="Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.", 
        image="img/pic-dol.png", 
    )
    serv_model.objects.create(
        pk=3,
        title="Maiores Alias Consequatur",
        content="Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.", 
        image="img/pic-diag.png", 
    )
    serv_model.objects.create(
        pk=4,
        title="Voluptatibus Maiores Alias",
        content="Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.", 
        image="img/pic-arr.png", 
    )
    serv_model.objects.create(
        pk=5,
        title="Dut Aut Reiciendis Maiores",
        content="Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.", 
        image="img/pic-hom.png", 
    )
    serv_model.objects.create(
        pk=6,
        title="Doloribus Volupta Maiores",
        content="Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.", 
        image="img/pic-set.png", 
    )

    news_model.objects.create(
        pk=1,
        data="2020-04-01 15:28:42.855490",
        news_tite="Fugiat Quo Voluptas", 
        news_content="Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse.", 
    )
    news_model.objects.create(
        pk=2,
        data="2020-04-03 14:28:42.855490",
        news_tite="FugQui In Ea Voluptate", 
        news_content="Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse.", 
    )
    news_model.objects.create(
        pk=3,
        data="2020-04-05 18:28:42.855490",
        news_tite="Autem Vel Eum Iure", 
        news_content="Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse.", 
    )
    news_model.objects.create(
        pk=4,
        data="2020-04-07 11:28:42.855490",
        news_tite="Itaque earum rerum hic", 
        news_content="Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse.", 
    )

    team_model.objects.create(
        pk=1,
        name="Mary Jane",
        post="Vestibulum", 
        img="img/team-mary.jpg", 
    )
    team_model.objects.create(
        pk=2,
        name="Peter Parker",
        post="Vestibulum", 
        img="img/team-peter.jpg", 
    )
    team_model.objects.create(
        pk=3,
        name="John Watson",
        post="Vestibulum", 
        img="img/team-johan.jpg", 
    )
    team_model.objects.create(
        pk=4,
        name="Steven Wilson",
        post="Vestibulum", 
        img="img/team-steven.jpg", 
    )


def reverse_func(apps, schema_editor):
    pro_cat_model = apps.get_model("mainapp", "ProductCategory")
    prod_model = apps.get_model("mainapp", "Product")
    soc_model = apps.get_model("mainapp", "MainSocial")
    serv_model = apps.get_model("mainapp", "Services")
    news_model = apps.get_model("mainapp", "News")
    team_model = apps.get_model("mainapp", "Team")  
      
    pro_cat_model.objects.all().delete()
    prod_model.objects.all().delete()
    soc_model.objects.all().delete()
    serv_model.objects.all().delete()
    news_model.objects.all().delete()
    team_model.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
